feat(UIKIT-1151): Добавлена утилита для форматирования валюты
kaluga-astral/utils pull request #3
Opened 2024-09-18 11:45 UTC by Cabagemage

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2024-09-19 11:29 UTC, mfrolov89 requested changes

2024-09-19 11:29 UTC, mfrolov89 commented on package/src/number/formatNumberToCurrency/formatNumberToCurrency.test.ts
> +describe('formatNumberToCurrency', () => {
стоит добавить тест на zeroSumPlaceholder

2024-09-19 11:29 UTC, mfrolov89 commented on package/src/number/formatNumberToCurrency/formatNumberToCurrency.ts
> + * **Параметры**
* Форматирует число в формат валюты.
 *
 * @param params - Параметры для форматирования.
 *
 * @param params.amount - Сумма в числовом или строковом формате.
 * @param params.currencyCode - Код валюты в формате [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217#List_of_ISO_4217_currency_codes).
 * @param params.isTextInsteadOfZeroFormat - Флаг для замены отображения "0 ₽" на текст. По умолчанию "Бесплатно".
 * @param params.zeroSumPlaceholder - Текст, который должен отображаться, если сумма равна "0". По умолчанию "Бесплатно".
 *

2024-09-19 11:29 UTC, mfrolov89 commented on package/src/number/formatNumberToCurrency/formatNumberToCurrency.ts
> +    isTextInsteadOfZeroFormat = false,
думаю тут нет необходимости по дефолту указывать false

2024-09-19 11:29 UTC, mfrolov89 commented on package/src/number/formatNumberToCurrency/formatNumberToCurrency.ts
> +    return 'Некорректное значение';
```suggestion
    return;
```
Иначе в рендер уйдет сообщение об ошибке. Кажется что такого быть не должно

2024-09-19 14:02 UTC, Cabagemage commented on package/src/number/formatNumberToCurrency/formatNumberToCurrency.test.ts
> +describe('formatNumberToCurrency', () => {
Добавлен с 31-ой строки

2024-09-20 06:42 UTC, mfrolov89 approved these changes

2024-09-20 07:51 UTC, merged